
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_DER = 38;
  public static final int COMP_MENOR_IGUAL = 45;
  public static final int TIPO = 2;
  public static final int DESPLEGAR = 15;
  public static final int ENTERO = 7;
  public static final int SI = 24;
  public static final int MATRIZ = 22;
  public static final int DESDE = 27;
  public static final int CORCHETE_DER = 40;
  public static final int RECIBE = 19;
  public static final int HASTA = 28;
  public static final int OP_DIV = 36;
  public static final int FIN_SI = 26;
  public static final int AND = 47;
  public static final int IDENTIFICADOR = 3;
  public static final int FIN_COMENTARIO = 13;
  public static final int MODULO_K = 18;
  public static final int SINO = 25;
  public static final int CARACTER = 23;
  public static final int DEVUELVE = 20;
  public static final int OR = 46;
  public static final int INICIO_BLOQUE = 10;
  public static final int MIENTRAS = 30;
  public static final int DECLARAR = 16;
  public static final int COMP_MENOR = 43;
  public static final int COMP_MAYOR = 42;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 17;
  public static final int CADENA = 4;
  public static final int COMP_DIFERENTE = 41;
  public static final int PAR_IZQ = 37;
  public static final int FIN_MIENTRAS = 31;
  public static final int VECTOR = 21;
  public static final int OP_IGUAL = 32;
  public static final int PROGRAMA_K = 9;
  public static final int CORCHETE_IZQ = 39;
  public static final int INICIO_COMENTARIO = 12;
  public static final int FIN_BLOQUE = 11;
  public static final int LEER = 14;
  public static final int BOOLEANO = 6;
  public static final int OP_MAS = 33;
  public static final int COMP_MAYOR_IGUAL = 44;
  public static final int FIN_DESDE = 29;
  public static final int CONT_COMENT = 5;
  public static final int FLOTANTE = 8;
  public static final int OP_POR = 35;
  public static final int OP_MENOS = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TIPO",
  "IDENTIFICADOR",
  "CADENA",
  "CONT_COMENT",
  "BOOLEANO",
  "ENTERO",
  "FLOTANTE",
  "PROGRAMA_K",
  "INICIO_BLOQUE",
  "FIN_BLOQUE",
  "INICIO_COMENTARIO",
  "FIN_COMENTARIO",
  "LEER",
  "DESPLEGAR",
  "DECLARAR",
  "COMA",
  "MODULO_K",
  "RECIBE",
  "DEVUELVE",
  "VECTOR",
  "MATRIZ",
  "CARACTER",
  "SI",
  "SINO",
  "FIN_SI",
  "DESDE",
  "HASTA",
  "FIN_DESDE",
  "MIENTRAS",
  "FIN_MIENTRAS",
  "OP_IGUAL",
  "OP_MAS",
  "OP_MENOS",
  "OP_POR",
  "OP_DIV",
  "PAR_IZQ",
  "PAR_DER",
  "CORCHETE_IZQ",
  "CORCHETE_DER",
  "COMP_DIFERENTE",
  "COMP_MAYOR",
  "COMP_MENOR",
  "COMP_MAYOR_IGUAL",
  "COMP_MENOR_IGUAL",
  "OR",
  "AND"
  };
}

